### ISSUE TITLE
Нет событий новых записей на стене

### ISSUE THREAD

**Issue by ImVad1k** [lxstvayne/vk_maria#4]
`@dp.event_handler(event_type=types.EventType.WALL_POST_NEW)
def new_msg(event):
    print(f'Новая запись на стене  {event.message.text}')`

А когда создаю запись в сообществе ничего не происходит

**Comment by lxstvayne** [comment]
Здравствуйте. Приложите минимально воспроизводимый пример кода, а также информацию какой тип токена вы используете.

**Comment by ImVad1k** [comment]
> Здравствуйте. Приложите минимально воспроизводимый пример кода, а также информацию какой тип токена вы используете.


Дело в том, что я перепутал типы событий для токенов людей и сообществ. Прошу прощения за беспокойство
